//! Tokens.
//!
//! A [`TokenKind`] is a small `Copy` tag. Crucially it does *not* carry the
//! literal's text or value — those are recovered from the source via the token's
//! [`Span`] when needed (e.g. `&src[token.span.range()]`). Keeping `TokenKind`
//! payload-free makes it `Copy`, makes the token stream cache-friendly, and keeps
//! a clean separation: the lexer classifies, later passes interpret.

use crate::span::Span;

#[derive(Clone, Copy, PartialEq, Eq, Debug)]
pub struct Token {
    pub kind: TokenKind,
    pub span: Span,
}

impl Token {
    pub fn new(kind: TokenKind, span: Span) -> Token {
        Token { kind, span }
    }
}

#[derive(Clone, Copy, PartialEq, Eq, Debug)]
pub enum TokenKind {
    // --- Literals & identifiers ---
    Ident,
    Int,
    Float,
    Str,
    Char,
    Underscore, // a lone `_`, used as the pattern wildcard

    // --- Keywords ---
    Fn,
    Let,
    Var,
    Const,
    Struct,
    Record,
    Enum,
    Union,
    Trait,
    Type,
    Distinct,
    Error, // the `error` keyword that names an error set
    Match,
    If,
    Else,
    For,
    In,
    While,
    Loop,
    Return,
    Break,
    Continue,
    Comptime,
    Region,
    Scope,
    Concurrent,
    Spawn,
    Await,
    Unsafe,
    Trusted,
    Extern,
    Import,
    Pub,
    Requires,
    Ensures,
    Invariant,
    Variant,
    Where,
    As,
    And,
    Or,
    Not,
    Dyn,
    Catch,
    // Parameter-passing conventions — the heart of the ownership model (§4.3).
    Read,
    Mut,
    Take,
    Out,
    True,
    False,
    Null,
    SelfValue, // `self`
    SelfType,  // `Self`

    // --- Punctuation & operators ---
    LParen,
    RParen,
    LBrace,
    RBrace,
    LBracket,
    RBracket,
    Comma,
    Semi,
    Colon,
    ColonColon,
    Dot,
    DotDot,
    DotDotEq,
    DotStar, // `.*` — pointer dereference (e.g. `(p + i).*`)
    Arrow,   // `->`
    FatArrow, // `=>`
    Plus,
    Minus,
    Star,
    Slash,
    Percent,
    Eq,
    EqEq,
    Ne,
    Lt,
    Le,
    Gt,
    Ge,
    Amp,
    AmpAmp,
    Pipe,
    PipePipe,
    Caret,
    Tilde,
    Shl,
    Shr,
    Bang,
    Question,
    At, // `@` introduces an attribute, e.g. `@volatile`, `@layout(c)`
    PlusEq,
    MinusEq,
    StarEq,
    SlashEq,
    PercentEq,
    AmpEq,
    PipeEq,
    CaretEq,

    // --- Sentinels ---
    Eof,
    Unknown, // an unrecognized character; a diagnostic was emitted
}

impl TokenKind {
    /// Map an identifier-shaped lexeme to its keyword kind, if it is one.
    pub fn keyword(ident: &str) -> Option<TokenKind> {
        use TokenKind::*;
        Some(match ident {
            "fn" => Fn,
            "let" => Let,
            "var" => Var,
            "const" => Const,
            "struct" => Struct,
            "record" => Record,
            "enum" => Enum,
            "union" => Union,
            "trait" => Trait,
            "type" => Type,
            "distinct" => Distinct,
            "error" => Error,
            "match" => Match,
            "if" => If,
            "else" => Else,
            "for" => For,
            "in" => In,
            "while" => While,
            "loop" => Loop,
            "return" => Return,
            "break" => Break,
            "continue" => Continue,
            "comptime" => Comptime,
            "region" => Region,
            "scope" => Scope,
            "concurrent" => Concurrent,
            "spawn" => Spawn,
            "await" => Await,
            "unsafe" => Unsafe,
            "trusted" => Trusted,
            "extern" => Extern,
            "import" => Import,
            "pub" => Pub,
            "requires" => Requires,
            "ensures" => Ensures,
            "invariant" => Invariant,
            "variant" => Variant,
            "where" => Where,
            "as" => As,
            "and" => And,
            "or" => Or,
            "not" => Not,
            "dyn" => Dyn,
            "catch" => Catch,
            "read" => Read,
            "mut" => Mut,
            "take" => Take,
            "out" => Out,
            "true" => True,
            "false" => False,
            "null" => Null,
            "self" => SelfValue,
            "Self" => SelfType,
            _ => return None,
        })
    }

    /// A short human-readable label, used in token dumps and (later) diagnostics.
    pub fn describe(self) -> &'static str {
        use TokenKind::*;
        match self {
            Ident => "ident",
            Int => "int",
            Float => "float",
            Str => "string",
            Char => "char",
            Underscore => "_",
            Fn => "fn",
            Let => "let",
            Var => "var",
            Const => "const",
            Struct => "struct",
            Record => "record",
            Enum => "enum",
            Union => "union",
            Trait => "trait",
            Type => "type",
            Distinct => "distinct",
            Error => "error",
            Match => "match",
            If => "if",
            Else => "else",
            For => "for",
            In => "in",
            While => "while",
            Loop => "loop",
            Return => "return",
            Break => "break",
            Continue => "continue",
            Comptime => "comptime",
            Region => "region",
            Scope => "scope",
            Concurrent => "concurrent",
            Spawn => "spawn",
            Await => "await",
            Unsafe => "unsafe",
            Trusted => "trusted",
            Extern => "extern",
            Import => "import",
            Pub => "pub",
            Requires => "requires",
            Ensures => "ensures",
            Invariant => "invariant",
            Variant => "variant",
            Where => "where",
            As => "as",
            And => "and",
            Or => "or",
            Not => "not",
            Dyn => "dyn",
            Catch => "catch",
            Read => "read",
            Mut => "mut",
            Take => "take",
            Out => "out",
            True => "true",
            False => "false",
            Null => "null",
            SelfValue => "self",
            SelfType => "Self",
            LParen => "(",
            RParen => ")",
            LBrace => "{",
            RBrace => "}",
            LBracket => "[",
            RBracket => "]",
            Comma => ",",
            Semi => ";",
            Colon => ":",
            ColonColon => "::",
            Dot => ".",
            DotDot => "..",
            DotDotEq => "..=",
            DotStar => ".*",
            Arrow => "->",
            FatArrow => "=>",
            Plus => "+",
            Minus => "-",
            Star => "*",
            Slash => "/",
            Percent => "%",
            Eq => "=",
            EqEq => "==",
            Ne => "!=",
            Lt => "<",
            Le => "<=",
            Gt => ">",
            Ge => ">=",
            Amp => "&",
            AmpAmp => "&&",
            Pipe => "|",
            PipePipe => "||",
            Caret => "^",
            Tilde => "~",
            Shl => "<<",
            Shr => ">>",
            Bang => "!",
            Question => "?",
            At => "@",
            PlusEq => "+=",
            MinusEq => "-=",
            StarEq => "*=",
            SlashEq => "/=",
            PercentEq => "%=",
            AmpEq => "&=",
            PipeEq => "|=",
            CaretEq => "^=",
            Eof => "<eof>",
            Unknown => "<unknown>",
        }
    }
}
